python3 train.py \
  --model_type small \
  --map_dir /home/ekaterina/Загрузки/project_data/map \
  --goal_dir /home/ekaterina/Загрузки/project_data/goal_structured \
  --heuristic_dir /home/ekaterina/Загрузки/project_data/heuristic_structured \
  --map_to_heuristic /home/ekaterina/Загрузки/project_data/data.json \
  --output_dir /home/ekaterina/Загрузки/project_data/results \
  --alpha 2.0 \
  --alpha1 5.0 \
  --alpha2 20.0 \
  --batch_size 16 \
  --learning_rate 1e-3 \
  --desired_batch_size 16 \
  --num_train_epochs 1